//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AmisGuiMFC2.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_PROPSHT_CAPTION             102
#define IDD_SIDEBAR                     103
#define IDS_META_TITLE                  103
#define IDS_META_AUTHOR                 104
#define IDS_META_PUBLISHER              105
#define IDS_META_DESCRIPTION            106
#define IDS_META_NARRATOR               107
#define IDS_META_TOTAL_DURATION         108
#define IDS_META_TOTAL_PAGES            109
#define IDS_META_DATE                   110
#define IDS_META_FORMAT                 111
#define IDS_META_FEATURES               112
#define IDS_META_CURRENT_PAGE           113
#define IDS_META_CURRENT_SECTION        114
#define IDS_META_MAX_SECTION_DEPTH      115
#define IDS_META_TOC_ENTRIES            116
#define IDS_META_SECTION_CONTENTS_LIST  117
#define IDS_META_SECTION_CONTENTS       118
#define IDS_NOT_AVAILABLE               119
#define IDS_SEARCHING                   120
#define IDS_SEARCH_STOPPED              121
#define IDS_NO_FILES_FOUND              122
#define ID_AMIS_FOCUS_ON_SIDEBAR        123
#define IDS_ONE_FILE_FOUND              123
#define IDS_FILES_FOUND                 124
#define IDS_NO_BOOKS_ON_CD              125
#define IDS_PLEASE_RESTART              126
#define ID_AMIS_FOCUS_ON_TEXT           127
#define IDR_MAINFRAME                   128
#define IDR_AMISTYPE                    129
#define ID_AMIS_INCREASE_SECTION_DEPTH  130
#define ID_AMIS_DECREASE_SECTION_DEPTH  131
#define ID_AMIS_RESET_HIGHLIGHT_COLORS  132
#define ID_AMIS_TOGGLE_AUDIO_CONTENT_PLAYBACK 133
#define ID_AMIS_TOGGLE_AUDIO_SELFVOICING_PLAYBACK 134
#define ID_AMIS_FIND_NEXT_IN_TEXT       143
#define ID_AMIS_FIND_PREVIOUS_IN_TEXT   144
#define ID_AMIS_DECREASE_CONTENT_VOLUME 145
#define ID_AMIS_DECREASE_UI_VOLUME      146
#define IDD_FIND                        147
#define ID_AMIS_INCREASE_CONTENT_VOLUME 147
#define ID_AMIS_INCREASE_UI_VOLUME      148
#define AMIS_VIEW_MENU_BASE_ID          150
#define IDI_AMIS                        164
#define IDD_SEARCHDAISY                 177
#define IDD_GOTOPAGE                    180
#define IDD_CDSEARCH                    181
#define IDD_PUBLICATIONSUMMARY          182
#define IDI_LANGICON                    185
#define IDB_BOOKSHELFMAG                186
#define IDD_OPENURL                     190
#define IDD_PREFERENCES                 191
#define IDD_TEXTSTYLE                   192
#define IDD_READING_OPTIONS             193
#define AMIS_RECENT_BOOK_BASE_ID        200
#define AMIS_SECTION_DEPTH_BASE_ID      250
#define AMIS_NAVLIST_BASE_ID            300
#define AMIS_PAGE_STYLE_BASE_ID         350
#define AMIS_BOOKMARKS_BASE_ID          400
#define ID_AMIS_NEXT_PAGE_STYLE         450
#define IDS_ERROR_OPENING_RELOADING     500
#define IDS_ERROR_OPENING               501
#define IDS_NAVIGATION                  502
#define IDS_SECTIONS                    503
#define IDS_PAGES                       504
#define IDS_FOOTNOTES                   505
#define IDS_PRODUCER_NOTES              506
#define IDS_SIDEBARS                    507
#define IDS_GROUPED_ITEMS               508
#define ID_AMBULANT_PLAY                700
#define IDC_TREE                        1000
#define IDC_TAB                         1001
#define IDC_SEARCHSTRING                1003
#define IDC_LIST_PAGE                   1015
#define IDC_TTSVOICES                   1020
#define IDC_STARTSEARCH                 1030
#define IDC_ISSELFVOICING               1034
#define IDC_BROWSE                      1038
#define IDC_LOADLASTBOOK                1041
#define IDC_HIGHLIGHTTEXT               1042
#define IDC_STARTINBASICVIEW            1043
#define IDC_STOPSEARCH                  1048
#define IDC_SEARCHING                   1051
#define IDC_FILESFOUND                  1052
#define IDC_PAGENUM                     1055
#define IDC_SEARCHPATH                  1056
#define IDC_BOOKLIST                    1058
#define IDC_OPENBOOK                    1059
#define IDC_LANGICON                    1065
#define IDC_FINDPREVIOUS                1069
#define IDC_SELTTSLABEL                 1072
#define IDC_PAUSEONLOSTFOCUS            1074
#define IDC_DISABLESCREENSAVER          1075
#define IDC_AMISNAME                    1076
#define IDC_COPYRIGHT                   1077
#define IDC_URL                         1079
#define IDC_SUMMARYLIST                 1085
#define IDC_SEARCHINSTRUCTIONS          1088
#define IDC_INSTALLEDLANGUAGES          1097
#define IDC_PUBLICATIONSUMMARYCAPTION   1100
#define IDC_AMISICON                    1101
#define IDC_MULTIVOLCD_INSTRUCTIONS     1103
#define IDC_GOTOPAGE_CAPTION            1104
#define IDC_OPENURL_CAPTION             1105
#define IDC_FONT                        1106
#define IDC_HIGHLIGHTFOREGROUND         1107
#define IDC_HIGHLIGHTBACKGROUND         1108
#define IDC_FONTLABEL                   1109
#define IDC_HIGHLIGHTFOREGROUNDLABEL    1110
#define IDC_HIGHLIGHTBACKGROUNDLABEL    1111
#define IDC_READING_OPTIONS_INSTRUCTIONS 1115
#define IDC_OPTIONS_LIST                1116
#define IDC_FIND_DESCRIPTION            1118
#define SELF_VOICING_PLAY_NEXT          6969
#define IDC_CURRLANG                    9002
#define IDC_VERSION                     9006
#define IDC_VERSIONNOTE                 9007
#define ID_AMIS_OPEN_FILE               32918
#define ID_AMIS_OPEN_URL                32919
#define ID_AMIS_CLOSE_BOOK              32920
#define ID_AMIS_LOAD_CD                 32921
#define ID_AMIS_SEARCH_LOCAL_DRIVES     32922
#define ID_AMIS_SHOW_PREFERENCES        32923
#define ID_AMIS_RECENT_BOOKS_EMPTY      32924
#define ID_AMIS_EXIT                    32925
#define ID_AMIS_TOGGLE_SIDEBAR          32926
#define ID_AMIS_TOGGLE_VIEW             32927
#define ID_AMIS_BIGGER_FONT             32929
#define ID_AMIS_SMALLER_FONT            32930
#define ID_AMIS_PLAYPAUSE               32931
#define ID_AMIS_ESCAPE                  32932
#define ID_AMIS_FASTER                  32933
#define ID_AMIS_SLOWER                  32934
#define ID_AMIS_RESET_SPEED             32935
#define ID_AMIS_INCREASE_VOLUME         32936
#define ID_AMIS_DECREASE_VOLUME         32937
#define ID_AMIS_PREVIOUS_SECTION        32938
#define ID_AMIS_NEXT_SECTION            32939
#define ID_AMIS_SECTION_DEPTH_EMPTY     32940
#define ID_AMIS_PREVIOUS_PHRASE         32941
#define ID_AMIS_NEXT_PHRASE             32942
#define ID_AMIS_PREVIOUS_PAGE           32943
#define ID_AMIS_NEXT_PAGE               32944
#define ID_AMIS_GOTO_PAGE               32945
#define ID_AMIS_FIND_IN_TEXT            32946
#define ID_AMIS_ADD_BOOKMARK            32947
#define ID_AMIS_SHOW_READING_OPTIONS    32948
#define ID_AMIS_SHOW_PUBLICATION_SUMMARY 32949
#define ID_AMIS_SHOW_HELP_CONTENTS      32950
#define ID_AMIS_ABOUT                   32951
#define ID_AMIS_SHOW_TEXTSTYLE          32953
#define ID_AMIS_NO_PAGE_STYLES          32954
#define ID_HELP_KEYBOARDSHORTCUTS       32957
#define ID_AMIS_SHOW_KEYBOARD_SHORTCUTS 32958
#define IDS_SELFOLDER_TITLE             61258
#define IDS_SELFOLDER_INSTR             61259
#define IDS_FOLDERDOESNOTEXIST          61279
#define IDS_FOLDERINVALID               61280
#define IDS_FOLDERCANTBECREATED         61281
#define IDS_FILE_OPEN_DAISY_BOOKS       61288

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        194
#define _APS_NEXT_COMMAND_VALUE         32964
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           149
#endif
#endif
