#!/bin/bash

echo "Please set the environment variable LION to point to your /lion/lionapp/trunk/lion directory"

## Linux
LSOF=$(lsof -p $$ | grep -E "/"$(basename $0)"$")
THIS_FILE_PATH=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
if [ $? -ne 0 ]; then
  ## OSX
  THIS_FILE_PATH=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi
THIS_DIR=$(dirname $THIS_FILE_PATH)

NCX_FILE=$THIS_DIR/book/z3986-mp3/speechgen.ncx

# replace the phonemic text with the text we started out with
sed s/Daisy/DAISY/g $NCX_FILE > /tmp/ncx1
sed s/okay/OK/g /tmp/ncx1 > /tmp/ncx2
sed s/[[inpt PHON]]_AO+mIY>.[[inpt TEXT]]/AMIS/g /tmp/ncx2 > /tmp/ncx3
sed s/Maximum/Max./g /tmp/ncx3 > /tmp/ncx4
sed s/Copyright /Copyright (c) /g /tmp/ncx4 > /tmp/ncx5
sed s/Control/Ctrl/g /tmp/ncx5 > /tmp/ncx6

cp /tmp/ncx6 $NCX_FILE


echo "IMPORTING AUDIO DATA TO THE LOCAL AMIS LION DB"
cd ${LION}/daisylion/config
python generate_config.py amis local > lion.cfg
cd ${LION}/daisylion/scripts
python import_audio_ncx.py -c ../config/lion.cfg eng-US $NCX_FILE

echo "AUDIO FILES ARE IN THE AMIS LION DB"
echo "EXPORTING XML FILE"

python export_amis_xml.py -c ../config/lion.cfg eng-US > /tmp/amisXml.xml
cd $THIS_DIR
xmllint --format /tmp/amisXml.xml > amisAccessibleUi.xml

mv ./book/z3986-mp3/*.mp3 ./audio
echo "Done filling in audio data."
echo ""
echo "Now use Audacity to trim the mp3 files"
echo ""

