#!/bin/bash

echo "Please set the environment variable LION to point to your /lion/lionapp/trunk/lion directory"
## Linux
LSOF=$(lsof -p $$ | grep -E "/"$(basename $0)"$")
THIS_FILE_PATH=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
if [ $? -ne 0 ]; then
  ## OSX
  THIS_FILE_PATH=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi
THIS_DIR=$(dirname $THIS_FILE_PATH)

cd ${LION}/daisylion/config
python generate_config.py amis local > lion.cfg
cd ${LION}/daisylion/scripts
python printstrings.py -d eng-US > /tmp/strings.xml

cd $THIS_DIR

XSLT_FILE=prepare_prompts_for_pipeline.xslt

xsltproc $XSLT_FILE /tmp/strings.xml > /tmp/strings.html

# find and replace for correct TTS pronunciation
sed s/DAISY/Daisy/g /tmp/strings.html > /tmp/strings1.html
sed s/OK/okay/g /tmp/strings1.html > /tmp/strings2.html
sed s/AMIS/"[[inpt PHON]]_AO+mIY>.[[inpt TEXT]]"/g /tmp/strings2.html > /tmp/strings3.html
sed s/Max\./Maximum/g /tmp/strings3.html > /tmp/strings4.html
sed s/Copyright[[:space:]]\(c\)/Copyright/g /tmp/strings4.html > /tmp/strings5.html
sed s/Ctrl/Control/g /tmp/strings5.html > /tmp/strings6.html
# fix release date and version number
sed s/31[[:space:]]October[[:space:]]2008/"13 February 2009"/g /tmp/strings6.html > /tmp/strings7.html
sed s/Beta[[:space:]]4/RC1/g /tmp/strings7.html > /tmp/strings8.html

cp /tmp/strings8.html /tmp/strings.html

xmllint --format /tmp/strings.html > amisPrompts.html

rm -rf book
rm -rf audio
mkdir book
mkdir audio
rm amisPrompts.xml
rm amisPromptsFixed.xml
rm amisAccessibleUiWithAudio.xml
echo ""
echo "Now use the pipeline to generate the TTS"
echo ""



