#!/bin/bash

echo "Please set the environment variable LION to point to your /lion/lionapp/trunk/lion directory"
## Linux
LSOF=$(lsof -p $$ | grep -E "/"$(basename $0)"$")
THIS_FILE_PATH=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
if [ $? -ne 0 ]; then
  ## OSX
  THIS_FILE_PATH=$(echo $LSOF | sed -E s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
fi
THIS_DIR=$(dirname $THIS_FILE_PATH)

cd ${LION}/daisylion/config
python generate_config.py amis local > lion.cfg
cd ${LION}/daisylion/scripts
python printstrings.py -d eng-US > /tmp/strings.xml

cd $THIS_DIR

XSLT_FILE=prepare_prompts_for_pipeline.xslt

xsltproc $XSLT_FILE /tmp/strings.xml > /tmp/strings.html

xmllint --format /tmp/strings.html > amisPrompts.html
rm -rf book
rm -rf audio
mkdir book
mkdir audio
rm amisPrompts.xml
rm amisPromptsFixed.xml
rm amisAccessibleUiWithAudio.xml
echo ""
echo "Now use the pipeline to generate the TTS"
echo ""



