//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AmisGuiMFC.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_PROPSHT_CAPTION             102
#define IDD_SIDEBAR                     103
#define IDD_PROPPAGE2                   106
#define IDD_PROPPAGE1                   110
#define IDD_PROPPAGE4                   112
#define ID_FOCUS_ON_SIDEBAR             123
#define ID_HEAR_LAST_PROMPT             124
#define ID_HEAR_INSTRUCTIONS            125
#define ID_HEAR_LAST_TEXT_ENTRY         126
#define ID_FOCUS_ON_TEXT                127
#define IDR_MAINFRAME                   128
#define IDR_AMISTYPE                    129
#define ID_INCREASE_SECTION_DEPTH       130
#define ID_DECREASE_SECTION_DEPTH       131
#define ID_RESET_HIGHLIGHT_COLORS       132
#define ID_TOGGLE_AUDIO_CONTENT_PLAYBACK        133
#define ID_TOGGLE_AUDIO_SELFVOICING_PLAYBACK		134
#define IDD_FIND                        147
#define VIEW_MENU_BASE_ID               150
#define IDD_SKIP                        153
#define IDI_AMIS                        164
#define IDD_SEARCHDAISY                 177
#define IDD_GOTOPAGE                    180
#define IDD_CDSEARCH                    181
#define IDD_FULLSUMMARY                 182
#define IDD_CURRENTPOSITION             183
#define IDD_NAVIGATIONOPTIONS           184
#define IDI_LANGICON                    185
#define IDD_PROPPAGE3                   185
#define IDB_BOOKSHELFMAG                186
#define BOOK_BASE_ID                    200
#define SECTION_DEPTH_BASE_ID           250
#define NAVLIST_BASE_ID                 300
#define ID_MENU_GOTO_PAGE               352
#define ID_MENU_FIND_IN_TEXT            353
#define BOOKMARKS_BASE_ID               400
#define IDC_TREE                        1000
#define IDC_TAB                         1001
#define IDC_SEARCHSTRING                1003
#define IDC_SUMMARY                     1004
#define IDC_BASIC                       1010
#define IDC_BTN_BORDER                  1011
#define IDC_BTN_TEXTBG                  1012
#define IDC_BTN_PAGEBG                  1013
#define IDC_LIST_PAGE                   1015
#define IDC_TTSVOICE                    1020
#define IDC_BTN_RESETCOLORS             1028
#define IDC_STARTSEARCH                 1030
#define IDC_BTN_TEXTFG                  1030
#define IDC_BTN_PAGEFG                  1032
#define IDC_SELFVOICING                 1034
#define IDC_PROMPTONBASICVIEW           1036
#define IDC_BMKDIR                      1037
#define IDC_BROWSE                      1038
#define IDC_LOADLASTDTB                 1041
#define IDC_STOPSEARCH                  1048
#define IDC_PICTURE                     1050
#define IDC_SEARCHING                   1051
#define IDC_FILESFOUND                  1052
#define IDC_SKIPS                       1054
#define IDC_PAGENUM                     1055
#define IDC_SEARCHPATH                  1056
#define IDC_BOOKLIST                    1058
#define IDC_OPENBOOK                    1059
#define IDC_CANCEL                      1060
#define IDC_LANGICON                    1065
#define IDC_BTN_SELECTLANG              1066
#define IDC_CANCELBUTTON                1067
#define IDC_FINDNEXT                    1068
#define IDC_FINDPREV                    1069
#define IDC_BMKDIRBROWSE                1069
#define IDC_BMKDIRLABEL                 1071
#define IDC_SELTTSLABEL                 1072
#define IDC_PHRASES                     1073
#define IDC_CONTRAST                    1074
#define IDC_LISTCAPTION                 1075
#define IDC_PHRASEPREVIEW               1075
#define IDC_CONTRASTPREVIEW             1076
#define IDC_AMISNAME                    1076
#define IDC_PAGEFG                      1077
#define IDC_COPYRIGHT                   1077
#define IDC_PAGEBG                      1078
#define IDC_TEXTFG                      1079
#define IDC_TEXTBG                      1080
#define IDC_BORDER                      1081
#define ID_MENU_FIND_IN_TEXT_NEXT       9000
#define IDC_LANGLIST                    9001
#define ID_MENU_FIND_IN_TEXT_PREV       9001
#define IDC_CURRLANG                    9002
#define IDC_VERSION                     9006
#define IDC_VERSIONNOTE                 9007
#define ID_MENU_FILE_LOADCD             32771
#define ID_MENU_FILE_SEARCHDRIVE        32772
#define ID_MENU_VIEW_BASIC              32776
#define ID_MENU_VIEW_LARGEFONT          32778
#define ID_MENU_VIEW_RESET              32779
#define ID_MENU_PLAY_PLAY               32787
#define ID_MENU_PLAY_PAUSE              32788
#define ID_MENU_PLAY_FASTER             32789
#define ID_MENU_PLAY_NORMALSPEED        32791
#define ID_MENU_HELP_HELP               32798
#define ID_MENU_INFO_SUMMARY            32800
#define ID_MENU_FILE_PREFERENCES        32802
#define ID_MENU_INFO_NAVOPTIONS         32804
#define ID_MENU_INFO_CURRENTPOSITION    32805
#define ID_MENU_VIEW_RESETFONT          32814
#define ID_VIEW_CONTRAST                32818
#define ID_MENU_VIEW_CONTRAST           32818
#define ID_MENU_PLAY_ESCAPE             32819
#define ID_MENU_INFO_SKIP               32820
#define ID_MENU_HELP_CONTENTS           32821
#define ID_MENU_PLAY_SLOWER             32822
#define ID_MENU_FILE_EXIT               32823
#define ID_MENU_VIEW_SIDEBAR_ONOFF      32825
#define ID_FILE_RECENT_EMPTY            32828
#define ID_EMPTY                        32830
#define ID_MENU_NAV_NEXTSECTION         32833
#define ID_MENU_NAV_PREVSECTION         32834
#define ID_MENU_NAV_PREVPHRASE          32835
#define ID_MENU_NAV_NEXTPHRASE          32836
#define ID_MENU_BMK_ADD                 32837
#define ID_MENU_FILE_OPEN               32838
#define ID_MENU_HELP_ABOUT              32839
#define ID_MENU_PLAY_VOLUP              32844
#define ID_MENU_PLAY_VOLDOWN            32845
#define ID_MENU_NAV_PREVPAGE            32854
#define ID_MENU_NAV_NEXTPAGE            32856
#define ID_MENU_NAV_FINDINTEXT          32859
#define ID_MENU_NAV_GOTOPAGE            32860
#define ID_MENU_PLAYPAUSE               32865
#define IDS_NOSKIP                      61245
#define IDS_SELFOLDER_TITLE             61258
#define IDS_SELFOLDER_INSTR             61259
#define IDS_FOLDERDOESNOTEXIST          61279
#define IDS_FOLDERINVALID               61280
#define IDS_FOLDERCANTBECREATED         61281
#define IDS_FILE_OPEN_DAISY_BOOKS       61288

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32866
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           140
#endif
#endif
