//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AmisLangpack.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_PROPSHT_CAPTION             102
#define IDD_SIDEBAR                     103
#define IDD_PROPPAGE2                   106
#define IDD_PROPPAGE1                   110
#define IDD_PROPPAGE3                   111
#define IDD_PROPPAGE4                   112
#define IDD_PROPPAGE5                   113
#define ID_FOCUS_ON_SIDEBAR             123
#define ID_HEAR_LAST_PROMPT             124
#define ID_HEAR_INSTRUCTIONS            125
#define ID_HEAR_LAST_TEXT_ENTRY         126
#define IDR_MAINFRAME                   128
#define IDR_AMISTYPE                    129
#define IDI_ICON_OPEN                   130
#define IDS_VERSION                     130
#define IDI_ICON_LOADCD                 131
#define IDI_ICON_INFO                   132
#define IDI_ICON_PAGENEXT               133
#define IDI_ICON_PAGEPREV               134
#define IDI_ICON_NEXT                   135
#define IDI_ICON_PREVIOUS               136
#define IDI_ICON_PREVPHR                137
#define IDI_ICON_NEXTPHR                138
#define IDI_ICON_PLAY                   139
#define IDI_ICON_PAUSE                  140
#define IDI_ICON_FONT                   142
#define IDI_ICON_COLOR                  143
#define IDI_ICON_BMK                    144
#define IDI_ICON_HELP                   145
#define IDD_SEARCH                      146
#define IDD_FIND                        147
#define IDD_MANAGEBMK                   148
#define IDD_EDITBMK                     149
#define VIEW_MENU_BASE_ID               150
#define IDD_SKIP                        153
#define IDI_ICON_TREEVIEW               156
#define IDI_ICON_PAGELIST               157
#define IDI_ICON_SPECIALLISTS           158
#define IDI_ICON_SEARCHRESULTS          162
#define IDI_ICON1                       163
#define IDI_AMIS                        164
#define IDI_DAISY                       169
#define IDI_PLUS                        171
#define IDI_CIRCLE                      172
#define IDI_MINUS                       173
#define IDD_SEARCHDAISY                 177
#define IDD_GOTOPAGE                    180
#define IDD_CDSEARCH                    181
#define IDD_FULLSUMMARY                 182
#define IDD_CURRENTPOSITION             183
#define IDD_NAVIGATIONOPTIONS           184
#define IDI_LANGICON                    185
#define IDB_BOOKSHELFMAG                186
#define IDS_VERSIONNOTE                 189
#define BOOK_BASE_ID                    200
#define SECTION_DEPTH_BASE_ID           250
#define NAVLIST_BASE_ID                 300
#define ID_MENU_PREV_PAGE               350
#define ID_MENU_NEXT_PAGE               351
#define ID_MENU_GOTO_PAGE               352
#define ID_MENU_FIND_IN_TEXT            353
#define BOOKMARKS_BASE_ID               400
#define IDC_TREE                        1000
#define IDC_TAB                         1001
#define IDC_EDIT1                       1003
#define IDC_SEARCHSTRING                1003
#define IDC_LIST1                       1004
#define IDC_BUTTON2                     1006
#define IDC_BUTTON3                     1007
#define IDC_EDIT2                       1008
#define IDC_BUTTON1                     1009
#define IDC_CHECK1                      1010
#define IDC_BASIC                       1010
#define IDC_CHECK2                      1011
#define IDC_BTN_BORDER                  1011
#define IDC_CHECK3                      1012
#define IDC_BTN_TEXTBG                  1012
#define IDC_CHECK4                      1013
#define IDC_BTN_PAGEBG                  1013
#define IDC_CHECK5                      1014
#define IDC_LIST_PAGE                   1015
#define IDC_LIST_SEARCHRESULTS          1018
#define IDC_USEAUDIOCLIPS               1018
#define IDC_USETTS                      1019
#define IDC_TTSVOICE                    1020
#define IDC_BUTTON4                     1021
#define IDC_BTN_BROWSE                  1023
#define IDC_SEARCH_PATH                 1026
#define IDC_BTN_RESETCOLORS             1028
#define IDC_STARTSEARCH                 1030
#define IDC_BTN_TEXTFG                  1030
#define IDC_ANIMATE1                    1031
#define IDC_BTN_PAGEFG                  1032
#define IDC_NOTIFYSKIPDESCRIBE          1032
#define IDC_NOTIFYSKIPSOUNDFX           1033
#define IDC_SELFVOICING                 1034
#define IDC_NOTIFYSKIP                  1035
#define IDC_PROMPTONBASICVIEW           1036
#define IDC_BMKDIR                      1037
#define IDC_BROWSE                      1038
#define IDC_AUDIODIR                    1039
#define IDC_BROWSE2                     1040
#define IDC_LOADLASTDTB                 1041
#define IDC_BASICVIEW                   1042
#define IDC_DEFAULTVIEW                 1043
#define IDC_PREVIEW_TEXT                1044
#define IDC_PREVIEW_CONTRAST            1045
#define IDC_STOPSEARCH                  1048
#define IDC_PICTURE                     1050
#define IDC_SEARCHING                   1051
#define IDC_FILESFOUND                  1052
#define IDC_SKIPS                       1054
#define IDC_PAGENUM                     1055
#define IDC_SEARCHPATH                  1056
#define IDC_BOOKLIST                    1058
#define IDC_OPENBOOK                    1059
#define IDC_CANCEL                      1060
#define IDC_SUMMARY_TEXT                1064
#define IDC_LANGICON                    1065
#define IDC_BTN_SELECTLANG              1066
#define IDC_CANCELBUTTON                1067
#define IDC_FINDNEXT                    1068
#define IDC_FINDPREV                    1069
#define IDC_BMKDIRBROWSE                1069
#define IDC_BMKDIRLABEL                 1071
#define IDC_SELTTSLABEL                 1072
#define ID_MENU_FIND_IN_TEXT_NEXT       9000
#define IDC_LANGLIST                    9001
#define ID_MENU_FIND_IN_TEXT_PREV       9001
#define IDC_CURRLANG                    9002
#define IDC_VERSION                     9006
#define IDC_VERSIONNOTE                 9007
#define ID_FILE_LOADCD                  32771
#define ID_MENU_FILE_LOADCD             32771
#define ID_FILE_SEARCHDRIVE             32772
#define ID_MENU_FILE_SEARCHDRIVE        32772
#define ID_VIEW_SIDEBAR                 32775
#define ID_VIEW_BASIC                   32776
#define ID_MENU_VIEW_BASIC              32776
#define ID_VIEW_LARGEFONT               32778
#define ID_MENU_VIEW_LARGEFONT          32778
#define ID_VIEW_RESET                   32779
#define ID_MENU_VIEW_RESET              32779
#define ID_VIEW_TEXT                    32780
#define ID_NAV_PHRASE                   32781
#define ID_NAV_CHAR                     32782
#define ID_NAV_WORD                     32783
#define ID_NAV_HEADING                  32784
#define ID_NAV_PAGE                     32786
#define ID_PLAY_PLAY                    32787
#define ID_MENU_PLAY_PLAY               32787
#define ID_PLAY_PAUSE                   32788
#define ID_MENU_PLAY_PAUSE              32788
#define ID_PLAY_FASTER                  32789
#define ID_MENU_PLAY_FASTER             32789
#define ID_PAUSE_SLOWER                 32790
#define ID_PLAY_NORMALSPEED             32791
#define ID_MENU_PLAY_NORMALSPEED        32791
#define ID_PLAY_SKIP                    32792
#define ID_OPTIONS_SKIP                 32793
#define ID_OPTIONS_SELFVOICING          32794
#define ID_OPTIONS_PLUGINS              32795
#define ID_OPTIONS_LANGUAGE             32796
#define ID_OPTIONS_KEYBOARD             32797
#define ID_HELP_HELP                    32798
#define ID_MENU_HELP_HELP               32798
#define ID_HELP_KEYBOARD                32799
#define ID_INFO_SUMMARY                 32800
#define ID_MENU_INFO_SUMMARY            32800
#define ID_INFO_WHEREAMI                32801
#define ID_FILE_PREFERENCES             32802
#define ID_MENU_FILE_PREFERENCES        32802
#define ID_NAV_FIND                     32803
#define ID_INFO_NAVOPTIONS              32804
#define ID_MENU_INFO_NAVOPTIONS         32804
#define ID_INFO_CURRENTSECTION          32805
#define ID_MENU_INFO_CURRENTPOSITION    32805
#define ID_INFO_CURRENTPAGE             32806
#define ID_BMK_ADDBMK                   32807
#define ID_BMK_ADDNOTE                  32808
#define ID_BMK_MANAGEBMK                32809
#define ID_NAV_GOTOPAGE                 32810
#define ID_VIEW_RESETFONT               32814
#define ID_MENU_VIEW_RESETFONT          32814
#define ID_VIEW_CONTRAST                32818
#define ID_MENU_VIEW_CONTRAST           32818
#define ID_PLAY_ESCAPE                  32819
#define ID_MENU_PLAY_ESCAPE             32819
#define ID_INFO_SKIP                    32820
#define ID_MENU_INFO_SKIP               32820
#define ID_HELP_CONTENTS                32821
#define ID_MENU_HELP_CONTENTS           32821
#define ID_PLAY_SLOWER                  32822
#define ID_MENU_PLAY_SLOWER             32822
#define ID_FILE_EXIT                    32823
#define ID_MENU_FILE_EXIT               32823
#define ID_VIEW_TOC                     32824
#define ID_VIEW_SIDEBAR_ONOFF           32825
#define ID_MENU_VIEW_SIDEBAR_ONOFF      32825
#define ID_VIEW_SEARCHRESULTS           32827
#define ID_FILE_RECENT_EMPTY            32828
#define ID_EMPTY                        32830
#define ID_MENU_NAV_NEXTSECTION         32833
#define ID_MENU_NAV_PREVSECTION         32834
#define ID_MENU_NAV_PREVPHRASE          32835
#define ID_MENU_NAV_NEXTPHRASE          32836
#define ID_MENU_BMK_ADD                 32837
#define ID_MENU_FILE_OPEN               32838
#define ID_MENU_HELP_ABOUT              32839
#define ID_MENU_PLAY_VOLUP              32844
#define ID_MENU_PLAY_VOLDOWN            32845
#define IDS_OPEN                        61216
#define IDS_LOADCD                      61217
#define IDS_PREVIOUS                    61218
#define IDS_NEXT                        61219
#define IDS_PLAY                        61220
#define IDS_PAUSE                       61221
#define IDS_PREVPHR                     61222
#define IDS_NEXTPHR                     61223
#define IDS_PAGEPREV                    61224
#define IDS_PAGENEXT                    61225
#define IDS_BMK                         61226
#define IDS_COLOR                       61227
#define IDS_FONT                        61228
#define IDS_INFO                        61229
#define IDS_HELP                        61230
#define IDS_SLOW                        61231
#define IDS_NORMAL                      61232
#define IDS_FAST                        61233
#define IDS_NAV_PAGE                    61234
#define IDS_NAV_NOTEREF                 61235
#define IDS_NAV_PRODNOTE                61236
#define IDS_NAV_SIDEBAR                 61237
#define IDS_NAV_GROUP                   61238
#define IDS_NAV_WINDOW                  61239
#define IDS_NAV_SECTION                 61240
#define IDS_SEARCHING                   61241
#define IDS_NOFILESFOUND                61242
#define IDS_ONEFILEFOUND                61243
#define IDS_NOSKIP                      61245
#define IDS_NEXT_GENERIC                61247
#define IDS_PREV_GENERIC                61248
#define IDS_MENU_NEXTPAGE               61249
#define IDS_MENU_PREVPAGE               61250
#define IDS_MENU_GOTO_PAGE              61251
#define IDS_MENU_FIND_IN_TEXT           61252
#define IDS_NAV_PAGES                   61253
#define IDS_NAV_NOTEREFS                61254
#define IDS_NAV_PRODNOTES               61255
#define IDS_NAV_SIDEBARS                61256
#define IDS_NAV_GROUPS                  61257
#define IDS_SELFOLDER_TITLE             61258
#define IDS_SELFOLDER_INSTR             61259
#define IDS_NOBOOKSFOUND                61260
#define IDS_NOCDLOADED                  61261
#define IDS_FS_TITLE                    61262
#define IDS_FS_AUTHOR                   61263
#define IDS_FS_PUBLISHER                61264
#define IDS_FS_DESC                     61265
#define IDS_FS_SECTIONS                 61266
#define IDS_FS_MAXDEPTH                 61267
#define IDS_FS_PAGEFRONT                61268
#define IDS_FS_PAGENORMAL               61269
#define IDS_FS_PAGESPECIAL              61270
#define IDS_FS_TOTALTIME                61271
#define IDS_CURRPOS                     61272
#define IDS_CURRPOS_PAGES               61273
#define IDS_CURRPOS_SUBSECTIONS         61274
#define IDS_NAVOPT                      61275
#define IDS_BOOKATPATHCHANGED           61276
#define IDS_HIGHLIGHTPREVIEW            61277
#define IDS_CONTRASTPREVIEW             61278
#define IDS_FOLDERDOESNOTEXIST          61279
#define IDS_FOLDERINVALID               61280
#define IDS_FOLDERCANTBECREATED         61281
#define IDS_X_FILESFOUND                61282
#define IDS_GENERALBOOKERROR            61283
#define IDS_DEFAULT_FONT                61284
#define IDS_PLUGINERROR_INIT            61285
#define IDS_PLUGINERROR_DLL             61286
#define IDS_FILE_OPEN_DAISY_BOOKS       61288
#define IDS_CURRLANG                    61289
#define IDS_RESTARTFORCHANGES           61290
#define IDS_BASICVIEWPROMPT             61291

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        190
#define _APS_NEXT_COMMAND_VALUE         32853
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           127
#endif
#endif
